all:    problem2

problem2: complexStruct.o
	gcc -o problem2 complexStruct.c

complexStruct.o: complexStruct.c
		 gcc -c complexStruct.c -o complexStruct.o


clean:
	rm -f problem2 complexStruct.o  core *~


