office-hours: office-hours.c
	gcc -lpthread $< -o $@
	#office-hours: office-hours.o office-hours.h
	#gcc -o office-hours office-hours.c -lpthread

clean:
	rm -f office-hours.c *.o *~ core
	#rm *.o office-hours
