
all:    problem3

problem3: memAllocation.c
	gcc -o problem3 memAllocation.c

memAllocation.o: memAllocation.c
		 gcc -c memAllocation.c -o memAllocation.o


clean:
	rm -f problem3 memAllocation.o  core *~


